"""The token mailed to an address, and the digest kept instead of it.

Both rules here come from OWASP's Forgot Password Cheat Sheet, which asks
of any such token that it be generated by a cryptographically secure
source, long enough to resist brute force, and stored "in a secure
manner". Each of those is measurable, so each is measured.
"""

import hashlib

from link_shortener.domain.value_objects.verification_token import (
    DIGEST_LENGTH,
    TOKEN_BYTES,
    issue_token,
    token_digest,
)


class TestTheTokenItself:
    """What is mailed has to be unguessable and safe in a URL."""

    def test_two_tokens_are_never_the_same(self):
        """A generator that repeats hands one person another's link."""
        assert len({issue_token() for _ in range(200)}) == 200

    def test_it_carries_enough_entropy_to_resist_guessing(self):
        """256 bits, measured through the alphabet rather than assumed.

        ``token_urlsafe`` returns base64 without padding, so the string is
        shorter than the byte count in hex would be -- checking the length
        against 32 would have been checking the wrong number.
        """
        assert TOKEN_BYTES == 32

        token = issue_token()
        bits = len(token) * 6  # base64: six bits per character
        assert bits >= 256, f"only {bits} bits of token"

    def test_it_comes_from_the_cryptographic_source(self):
        """The rule the other two tests here cannot see.

        Length and uniqueness are properties of the alphabet, not of the
        generator: ``random.choices`` over the same 64 characters produces
        43-character strings that never repeat in a sample of 200 and pass
        both. It is Mersenne Twister underneath -- observe a handful of
        outputs, recover the state, predict the next token, and confirm
        somebody else's address with it. What has to be pinned is where
        the bytes come from.
        """
        from unittest.mock import patch

        from link_shortener.domain.value_objects import verification_token

        with patch.object(
            verification_token.secrets, "token_urlsafe", return_value="fixed"
        ) as source:
            assert verification_token.issue_token() == "fixed"

        source.assert_called_once_with(TOKEN_BYTES)

    def test_it_survives_a_url_unchanged(self):
        """It travels in a query string; anything needing escaping there
        would arrive re-encoded and stop matching its own digest."""
        from urllib.parse import quote

        token = issue_token()

        assert quote(token, safe="") == token


class TestTheStoredDigest:
    """A leaked row must not be usable as the link it stands for."""

    def test_the_digest_is_sha256_of_the_token(self):
        """Compared against hashlib directly, not against the function
        under test applied twice -- which would agree with itself no
        matter what it computed."""
        token = "a-known-token"

        assert token_digest(token) == hashlib.sha256(b"a-known-token").hexdigest()

    def test_the_digest_does_not_contain_the_token(self):
        token = issue_token()

        assert token not in token_digest(token)

    def test_the_same_token_always_digests_alike(self):
        """Lookup is by digest; a salted hash would never match."""
        token = issue_token()

        assert token_digest(token) == token_digest(token)

    def test_different_tokens_digest_differently(self):
        assert token_digest(issue_token()) != token_digest(issue_token())

    def test_the_declared_width_is_what_the_column_must_hold(self):
        """The width lives in three places -- this rule, the ORM model and
        the migration. Checked against a real digest, so the constant
        cannot drift away from what it describes."""
        assert DIGEST_LENGTH == 64
        assert len(token_digest(issue_token())) == DIGEST_LENGTH
