
from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class RequestContext:
    """
    Immutable data class holding metadata about an incoming HTTP request.

    This object is passed through the application layers to provide
    contextual information for logging, auditing, and request tracing.
    """
    request_id: str
    """Unique identifier for the request (e.g., generated by middleware)."""

    remote_addr: Optional[str] = None
    """Client IP address, extracted with proxy awareness."""

    user_agent: Optional[str] = None
    """User-Agent string from the request headers."""

    request_path: Optional[str] = None
    """Path of the request (e.g., '/api/v1/shorten')."""

    request_method: Optional[str] = None
    """HTTP method (GET, POST, etc.)."""